spring.application.name=anexo1_referenciacontrareferencia

server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/db_referencia
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
security.jwt.key.private=123

# desactivar eureka
eureka.client.enabled=false