spring.application.name=anexo1_referenciacontrareferencia
server.port=8086

spring.datasource.url=${DB_URL_PROD}
spring.datasource.username=${DB_USER_PROD}
spring.datasource.password=${DB_PASS_PROD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none

security.jwt.key.private=${JWT_SECRET_PROD}

eureka.client.enabled=false
